// Frontend/department-crud-frontend-angular/src/app/components/department-list/department-list.component.ts
import { Component, Output, EventEmitter, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DepartmentService, Department } from '../../services/department.service';

@Component({
  selector: 'app-department-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './department-list.component.html',
})
export class DepartmentListComponent implements OnInit {
  departments: Department[] = [];

  @Output() editDepartment = new EventEmitter<Department>();
  @Output() createDepartment = new EventEmitter<void>();
  @Output() refresh = new EventEmitter<void>();

  constructor(private departmentService: DepartmentService, private cdr: ChangeDetectorRef) {}


  ngOnInit() {
    this.loadDepartments();
  }

  loadDepartments() {
    this.departmentService.getDepartment().subscribe((data) => {
      this.departments = data;
    });
  }

  deleteDepartment(id: number) {
  this.departmentService.deleteDepartment(id.toString()).subscribe(() => {
    console.log("Before Delete:", this.departments);
    this.departments = this.departments.filter(dept => dept.id !== id);
    console.log("After Delete:", this.departments);
    this.cdr.detectChanges(); // ✅ Force UI update
  });
}


  edit(department: Department) {
    this.editDepartment.emit(department);
  }
}


<div class="max-w-5xl mx-auto mt-10">
    <div class="flex justify-between items-center mb-5">
        <h1 class="text-3xl font-bold">Department List</h1>
        <button class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" (click)="createDepartment.emit()">
            Create Department
        </button>
    </div>

    <table class="w-full border border-gray-300 shadow-md bg-white">
        <thead class="bg-gray-200">
            <tr>
                <th class="py-2 px-4">ID</th>
                <th class="py-2 px-4">Name</th>
                <th class="py-2 px-4">Location</th>
                <th class="py-2 px-4">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let dep of departments" class="border-t hover:bg-gray-100 transition">
                <td class="py-2 px-4 text-center">{{ dep.id }}</td>
                <td class="py-2 px-4">{{ dep.name }}</td>
                <td class="py-2 px-4">{{ dep.location }}</td>
                <td class="py-2 px-4 flex justify-center gap-2">
                    <button class="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600"
                        (click)="edit(dep)">Edit</button>
                    <button class="bg-red-500 text-white px-3 py-1 rounded hover:bg-red-600"
                        (click)="deleteDepartment(dep.id!)">
                        Delete
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

// Frontend/department-crud-frontend-react/src/components/DepartmentList.tsx
import { Department } from "../types/types";

const DepartmentList = ({
  departments,
  onEdit,
  onCreate,
  onDelete,
}: {
  departments: Department[];
  onEdit: (department: Department) => void;
  onCreate: () => void;
  onDelete: (id: number) => void;
}) => {
  return (
    <div className="max-w-5xl mx-auto mt-10">
      <div className="flex justify-between items-center mb-5">
        <h1 className="text-3xl font-bold">Department List</h1>
        <button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" onClick={onCreate}>
          Create Department
        </button>
      </div>
      <table className="w-full border border-gray-300 shadow-md bg-white">
        <thead className="bg-gray-200">
          <tr>
            <th className="py-2 px-4">ID</th>
            <th className="py-2 px-4">Name</th>
            <th className="py-2 px-4">Location</th>
            <th className="py-2 px-4">Actions</th>
          </tr>
        </thead>
        <tbody>
          {departments.map((dept) => (
            <tr key={dept.id} className="border-t hover:bg-gray-100 transition">
              <td className="py-2 px-4 text-center">{dept.id}</td>
              <td className="py-2 px-4">{dept.name}</td>
              <td className="py-2 px-4">{dept.location}</td>
              <td className="py-2 px-4 flex justify-center gap-2">
                <button className="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600" onClick={() => onEdit(dept)}>
                  Edit
                </button>
                <button className="bg-red-500 text-white px-3 py-1 rounded hover:bg-red-600" onClick={() => onDelete(dept.id!)}>
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default DepartmentList;
