// Frontend/department-crud-frontend-angular/src/app/components/department-form/department-form.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DepartmentService, Department } from '../../services/department.service';

@Component({
  selector: 'app-department-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './department-form.component.html',
})
export class DepartmentFormComponent {
  @Input() department: Department = {
    id: undefined, // ✅ Ensure id is defined
    name: '',
    location: '',
  };

  @Output() refresh = new EventEmitter<void>(); // ✅ Emits an event to refresh the list
  @Output() close = new EventEmitter<void>(); // ✅ Emits an event to close the modal

  constructor(private departmentService: DepartmentService) {}

  saveDepartment() {
  const departmentData = { ...this.department };

  if (!departmentData.id) {
    delete departmentData.id; // ✅ Remove id when creating
  }

  if (this.department.id) {
    this.departmentService.updateDepartment(this.department.id.toString(), departmentData).subscribe(() => {
      this.refresh.emit(); // ✅ Refresh list after update
      this.close.emit(); // ✅ Close modal
    });
  } else {
    this.departmentService.createDepartment(departmentData).subscribe(() => {
      this.refresh.emit(); // ✅ Refresh list after creating
      this.close.emit();
    });
  }
}


}

<div class="p-5 w-[400px] bg-white rounded-lg shadow-lg">
    <h2 class="text-xl font-semibold text-center mb-4">
        {{ department.id ? 'Edit Department' : 'Create Department' }}
    </h2>

    <input type="text" [(ngModel)]="department.name" placeholder="Name" class="w-full p-3 border rounded mb-3"
        required />
    <input type="text" [(ngModel)]="department.location" placeholder="Location" class="w-full p-3 border rounded mb-3"
        required />

    <button class="w-full p-3 text-white bg-blue-500 rounded hover:bg-blue-600" (click)="saveDepartment()">
        <span class="text-white font-bold">
            {{ department.id ? 'Update' : 'Create' }}
        </span>
    </button>

</div>

// Frontend/department-crud-frontend-react/src/components/DepartmentForm.tsx
import { useState, useEffect } from "react";
import { Department } from "../types/types";


const DepartmentForm = ({
  department,
  onSave,
  onClose,
}: {
  department?: Department;
  onSave: (department: Department) => void;
  onClose: () => void;
}) => {
  const [formData, setFormData] = useState<Department>({
    name: "",
    location: "",
  });

  useEffect(() => {
    if (department) {
      setFormData(department);
    } else {
      setFormData({ name: "", location: "" });
    }
  }, [department]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData); // Call save function
    onClose(); // ✅ Close modal after saving
  };

  return (
    <div>
      <h2 className="text-xl font-semibold text-center mb-4">{department ? "Edit Department" : "Create Department"}</h2>
      <form onSubmit={handleSubmit} className="space-y-3">
        <input type="text" name="name" value={formData.name} onChange={handleChange} placeholder="Name" className="w-full p-2 border rounded" required />
        <input type="text" name="location" value={formData.location} onChange={handleChange} placeholder="Location" className="w-full p-2 border rounded" required />
        <button type="submit" className="w-full p-2 text-white bg-blue-500 rounded hover:bg-blue-600">{department ? "Update" : "Create"}</button>
      </form>
    </div>
  );
};

export default DepartmentForm;
