// Frontend/employee-crud-frontend-react/src/components/EmployeeList.tsx
import { Employee } from "../types/types";


const EmployeeList = ({
  employees,
  onEdit,
  onCreate,
  onDelete,
}: {
  employees: Employee[];
  onEdit: (employee: Employee) => void;
  onCreate: () => void;
  onDelete: (id: number) => void;
}) => {
  return (
    <div className="max-w-5xl mx-auto mt-10">
      <div className="flex justify-between items-center mb-5">
        <h1 className="text-3xl font-bold">Employee List</h1>
        <button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" onClick={onCreate}>
          Create Emp
        </button>
      </div>
      <table className="w-full border border-gray-300 shadow-md bg-white">
        <thead className="bg-gray-200">
          <tr>
            <th className="py-2 px-4">ID</th>
            <th className="py-2 px-4">Name</th>
            <th className="py-2 px-4">Email</th>
            <th className="py-2 px-4">Department</th>
            <th className="py-2 px-4">Salary ($)</th>
            <th className="py-2 px-4">Actions</th>
          </tr>
        </thead>
        <tbody>
          {employees.map((emp) => (
            <tr key={emp.id} className="border-t hover:bg-gray-100 transition">
              <td className="py-2 px-4 text-center">{emp.id}</td>
              <td className="py-2 px-4">{emp.name}</td>
              <td className="py-2 px-4">{emp.email}</td>
              <td className="py-2 px-4">{emp.department}</td>
              <td className="py-2 px-4 text-right">${emp.salary.toLocaleString()}</td>
              <td className="py-2 px-4 flex justify-center gap-2">
                <button className="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600" onClick={() => onEdit(emp)}>
                  Edit
                </button>
                <button className="bg-red-500 text-white px-3 py-1 rounded hover:bg-red-600" onClick={() => onDelete(emp.id!)}>
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default EmployeeList;

// Frontend/employee-crud-frontend-angular/src/app/components/employee-list/employee-list.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EmployeeService } from '../../services/employee.service';


@Component({
  selector: 'app-employee-list',
  standalone: true,
  imports: [CommonModule], // ✅ Ensure CommonModule is imported
  templateUrl: './employee-list.component.html',
})
export class EmployeeListComponent implements OnInit {
  @Output() editEmployee = new EventEmitter<any>();
  @Output() createEmployee = new EventEmitter<void>();

  employees: any[] = [];

  constructor(private employeeService: EmployeeService) {}

  ngOnInit() {
    this.loadEmployees();
  }

  loadEmployees() {
    this.employeeService.getEmployees().subscribe((data) => {
      this.employees = data;
    });
  }

  deleteEmployee(id: string) {
    this.employeeService.deleteEmployee(id).subscribe(() => this.loadEmployees());
  }

  edit(emp: any) {
    this.editEmployee.emit(emp);
  }
}

<div class="max-w-5xl mx-auto mt-10">
    <div class="flex justify-between items-center mb-5">
        <h1 class="text-3xl font-bold">Employee List</h1>
        <button class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600" (click)="createEmployee.emit()">
            Create Emp
        </button>
    </div>

    <table class="w-full border border-gray-300 shadow-md bg-white">
        <thead class="bg-gray-200">
            <tr>
                <th class="py-2 px-4">ID</th>
                <th class="py-2 px-4">Name</th>
                <th class="py-2 px-4">Email</th>
                <th class="py-2 px-4">Department</th>
                <th class="py-2 px-4">Salary ($)</th>
                <th class="py-2 px-4">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let emp of employees" class="border-t hover:bg-gray-100 transition">
                <td class="py-2 px-4 text-center">{{ emp.id }}</td>
                <td class="py-2 px-4">{{ emp.name }}</td>
                <td class="py-2 px-4">{{ emp.email }}</td>
                <td class="py-2 px-4">{{ emp.department }}</td>
                <td class="py-2 px-4 text-right">${{ emp.salary }}</td>
                <td class="py-2 px-4 flex gap-2">
                    <button class="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600"
                        (click)="edit(emp)">Edit</button>
                    <button class="bg-red-500 text-white px-3 py-1 rounded hover:bg-red-600"
                        (click)="deleteEmployee(emp.id!)">
                        Delete
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
