// Frontend/employee-crud-frontend-react/src/components/Modal.tsx
import { ReactNode } from "react";

const Modal = ({ isOpen, onClose, children }: { isOpen: boolean; onClose: () => void; children: ReactNode }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
      <div className="bg-white p-5 rounded shadow-lg w-96">
        <button
          className="absolute top-2 right-2 text-gray-600 hover:text-gray-900"
          onClick={onClose}
        >
          ✖
        </button>
        {children}
      </div>
    </div>
  );
};

export default Modal;

// Frontend/employee-crud-frontend-angular/src/app/components/modal/modal.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-modal',
  standalone: true, // ✅ Ensures it's a standalone component
  imports: [CommonModule], // ✅ Import CommonModule for Angular directives
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.css']
})
export class ModalComponent {
  @Output() onClose = new EventEmitter<void>(); // ✅ Emits an event to close the modal
}

<div class="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
    <div class="bg-white p-5 rounded shadow-lg w-96 relative">
        <button class="absolute top-2 right-2 text-gray-600 hover:text-gray-900" (click)="onClose.emit()">✖</button>
        <ng-content></ng-content>
    </div>
</div>
