// Frontend/employee-crud-frontend-react/src/components/EmployeeForm.tsx
import { useState, useEffect } from "react";
import { Employee } from "../types/types";


const EmployeeForm = ({
  employee,
  onSave,
  onClose,
}: {
  employee?: Employee;
  onSave: (employee: Employee) => void;
  onClose: () => void;
}) => {
  const [formData, setFormData] = useState<Employee>({
    name: "",
    email: "",
    department: "",
    salary: 0,
  });

  useEffect(() => {
    if (employee) {
      setFormData(employee);
    } else {
      setFormData({ name: "", email: "", department: "", salary: 0 });
    }
  }, [employee]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: name === "salary" ? Number(value) : value });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData); // Call save function
    onClose(); // ✅ Close modal after saving
  };

  return (
    <div>
      <h2 className="text-xl font-semibold text-center mb-4">{employee ? "Edit Employee" : "Create Employee"}</h2>
      <form onSubmit={handleSubmit} className="space-y-3">
        <input type="text" name="name" value={formData.name} onChange={handleChange} placeholder="Name" className="w-full p-2 border rounded" required />
        <input type="email" name="email" value={formData.email} onChange={handleChange} placeholder="Email" className="w-full p-2 border rounded" required />
        <input type="text" name="department" value={formData.department} onChange={handleChange} placeholder="Department" className="w-full p-2 border rounded" required />
        <input type="number" name="salary" value={formData.salary} onChange={handleChange} placeholder="Salary" className="w-full p-2 border rounded" required min="0" />
        <button type="submit" className="w-full p-2 text-white bg-blue-500 rounded hover:bg-blue-600">{employee ? "Update" : "Create"}</button>
      </form>
    </div>
  );
};

export default EmployeeForm;

// Frontend/employee-crud-frontend-angular/src/app/components/employee-form/employee-form.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

export interface Employee {
  id?: string;  // ✅ Make id optional
  name: string;
  email: string;
  department: string;
  salary: number;
}

@Component({
  selector: 'app-employee-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './employee-form.component.html',
})
export class EmployeeFormComponent {
  @Input() employee: Employee = {
    id: undefined, // ✅ Ensure id is defined
    name: '',
    email: '',
    department: '',
    salary: 0,
  };

  @Output() refresh = new EventEmitter<void>();
  @Output() close = new EventEmitter<void>();

  saveEmployee() {
    console.log('Saving Employee:', this.employee);
  }
}

<div class="p-5">
    <h2 class="text-xl font-semibold text-center">
        {{ employee.id ? 'Edit Employee' : 'Create Employee' }}
    </h2>
    <input type="text" [(ngModel)]="employee.name" placeholder="Name" class="w-full p-2 border rounded" required />
    <input type="email" [(ngModel)]="employee.email" placeholder="Email" class="w-full p-2 border rounded" required />
    <input type="text" [(ngModel)]="employee.department" placeholder="Department" class="w-full p-2 border rounded"
        required />
    <input type="number" [(ngModel)]="employee.salary" placeholder="Salary" class="w-full p-2 border rounded"
        required />

    <button class="w-full p-2 text-white bg-blue-500 rounded hover:bg-blue-600" (click)="saveEmployee()">
        {{ employee.id ? 'Update' : 'Create' }}
    </button>
</div>
